/**
 * Phase 2 Sprint 2 — Backtest Results Page
 * Shows per-symbol backtest signal history with action badges and
 * a summary stats row (confidence, composite score).
 */

import React, { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { getBacktestList, getBacktest } from "../services/api.js";

const ACTION_COLORS = {
  buy:  { background: "rgba(72,199,142,0.15)", color: "#48c78e" },
  sell: { background: "rgba(241,70,104,0.15)",  color: "#f14668" },
  hold: { background: "rgba(100,100,120,0.15)", color: "var(--muted)" },
};

function SignalBadge({ action }) {
  const style = ACTION_COLORS[action] || ACTION_COLORS.hold;
  return (
    <span style={{ ...style, borderRadius: 6, padding: "2px 8px", fontSize: 12, fontWeight: 600 }}>
      {action?.toUpperCase()}
    </span>
  );
}

function SymbolDetail({ symbol }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["backtest", symbol],
    queryFn: () => getBacktest(symbol),
    enabled: !!symbol,
    staleTime: 60_000,
  });

  if (isLoading) return <p style={{ color: "var(--muted)" }}>Loading {symbol}…</p>;
  if (isError)   return <p style={{ color: "#f14668" }}>No backtest data for {symbol}.</p>;
  if (!data?.signals?.length) return <p style={{ color: "var(--muted)" }}>No signals recorded yet.</p>;

  const { signals, signal_count } = data;
  const avgConf = signals.reduce((s, r) => s + (r.confidence || 0), 0) / signals.length;
  const avgComp = signals.reduce((s, r) => s + (r.composite_score || 0), 0) / signals.length;
  const buys    = signals.filter(s => s.action === "buy").length;
  const sells   = signals.filter(s => s.action === "sell").length;

  return (
    <div>
      <div style={styles.statRow}>
        {[
          ["Signals",    signal_count],
          ["Buys",       buys],
          ["Sells",      sells],
          ["Avg Conf",   `${(avgConf * 100).toFixed(1)}%`],
          ["Avg Score",  avgComp.toFixed(1)],
        ].map(([label, val]) => (
          <div key={label} style={styles.stat}>
            <div style={styles.statVal}>{val}</div>
            <div style={styles.statLabel}>{label}</div>
          </div>
        ))}
      </div>

      <div style={styles.tableWrap}>
        <table style={styles.table}>
          <thead>
            <tr>
              {["Date", "Action", "Confidence", "Score", "Source", "Rationale"].map(h => (
                <th key={h} style={styles.th}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {signals.map((sig) => (
              <tr key={sig.id} style={styles.tr}>
                <td style={styles.td}>{sig.created_at ? new Date(sig.created_at).toLocaleDateString() : "—"}</td>
                <td style={styles.td}><SignalBadge action={sig.action} /></td>
                <td style={styles.td}>{sig.confidence ? `${(sig.confidence * 100).toFixed(0)}%` : "—"}</td>
                <td style={styles.td}>{sig.composite_score ? Number(sig.composite_score).toFixed(1) : "—"}</td>
                <td style={styles.td}>
                  <span style={{ fontSize: 11, color: "var(--muted)" }}>{sig.source}</span>
                </td>
                <td style={{ ...styles.td, maxWidth: 300, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                  {sig.rationale || "—"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default function BacktestPage() {
  const [selected, setSelected] = useState(null);

  const { data: symbols = [], isLoading } = useQuery({
    queryKey: ["backtestList"],
    queryFn: getBacktestList,
    staleTime: 120_000,
  });

  return (
    <div>
      <h2 style={styles.heading}>Backtest Results</h2>
      <p style={{ color: "var(--muted)", marginBottom: 24 }}>
        Historical signals generated by the bot. Select a symbol to inspect its signal history.
      </p>

      {isLoading ? (
        <p style={{ color: "var(--muted)" }}>Loading symbols…</p>
      ) : symbols.length === 0 ? (
        <div style={styles.empty}>
          No backtest data available yet. The bot will populate this after its first analysis run.
        </div>
      ) : (
        <div style={styles.symbolRow}>
          {symbols.map((s) => (
            <button
              key={s.ticker}
              style={{ ...styles.chip, ...(selected === s.ticker ? styles.chipActive : {}) }}
              onClick={() => setSelected(s.ticker)}
            >
              {s.ticker}
              <span style={styles.chipCount}>{s.signal_count}</span>
            </button>
          ))}
        </div>
      )}

      {selected && (
        <div style={styles.card}>
          <h3 style={styles.cardTitle}>{selected} — Signal History</h3>
          <SymbolDetail symbol={selected} />
        </div>
      )}
    </div>
  );
}

const styles = {
  heading:    { fontSize: 24, fontWeight: 700, marginBottom: 8 },
  empty:      { color: "var(--muted)", padding: 24, background: "var(--surface)", borderRadius: 12, textAlign: "center" },
  symbolRow:  { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 24 },
  chip:       { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 20, padding: "6px 14px", cursor: "pointer", color: "var(--fg)", display: "flex", alignItems: "center", gap: 6, fontSize: 13 },
  chipActive: { background: "rgba(102,126,234,0.15)", borderColor: "var(--accent)", color: "var(--accent)" },
  chipCount:  { background: "var(--border)", borderRadius: 10, padding: "1px 6px", fontSize: 11 },
  card:       { background: "var(--surface)", borderRadius: 12, padding: 24 },
  cardTitle:  { fontSize: 18, fontWeight: 600, marginBottom: 20 },
  statRow:    { display: "flex", gap: 16, marginBottom: 24, flexWrap: "wrap" },
  stat:       { background: "var(--bg)", borderRadius: 8, padding: "12px 20px", minWidth: 90, textAlign: "center" },
  statVal:    { fontSize: 22, fontWeight: 700 },
  statLabel:  { fontSize: 11, color: "var(--muted)", marginTop: 2 },
  tableWrap:  { overflowX: "auto" },
  table:      { width: "100%", borderCollapse: "collapse" },
  th:         { textAlign: "left", padding: "8px 12px", borderBottom: "1px solid var(--border)", fontSize: 12, color: "var(--muted)", fontWeight: 600 },
  tr:         { borderBottom: "1px solid var(--border)" },
  td:         { padding: "10px 12px", fontSize: 13 },
};
